import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import type { Order, OrderWithItems, OrderStatus, PaymentMethod, CartItem, ItemSnapshot } from '@/types/database';
import { useEffect } from 'react';

export function useOrder(orderReference: string) {
  return useQuery({
    queryKey: ['order', orderReference],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('orders')
        .select(`
          *,
          order_items(*, menu_items(*)),
          payment_proofs(*)
        `)
        .eq('order_reference', orderReference)
        .maybeSingle();
      
      if (error) throw error;
      if (!data) return null;
      
      // Transform the data to match our types
      return {
        ...data,
        order_items: data.order_items.map((item: any) => ({
          ...item,
          item_snapshot: item.item_snapshot as ItemSnapshot,
        })),
      } as OrderWithItems;
    },
    enabled: !!orderReference,
  });
}

export function useOrders(status?: OrderStatus) {
  const queryClient = useQueryClient();

  const query = useQuery({
    queryKey: ['orders', status],
    queryFn: async () => {
      let q = supabase
        .from('orders')
        .select(`
          *,
          order_items(*, menu_items(*)),
          payment_proofs(*)
        `)
        .order('created_at', { ascending: false });
      
      if (status) {
        q = q.eq('status', status);
      }
      
      const { data, error } = await q;
      
      if (error) throw error;
      
      // Transform the data to match our types
      return (data || []).map((order: any) => ({
        ...order,
        order_items: order.order_items.map((item: any) => ({
          ...item,
          item_snapshot: item.item_snapshot as ItemSnapshot,
        })),
      })) as OrderWithItems[];
    },
  });

  // Real-time subscription for order updates
  useEffect(() => {
    const channel = supabase
      .channel('orders-realtime')
      .on(
        'postgres_changes',
        {
          event: '*',
          schema: 'public',
          table: 'orders',
        },
        () => {
          queryClient.invalidateQueries({ queryKey: ['orders'] });
        }
      )
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  }, [queryClient]);

  return query;
}

export function useCreateOrder() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({
      venueId,
      tableId,
      tableNumber,
      customerName,
      paymentMethod,
      items,
    }: {
      venueId?: string;
      tableId?: string;
      tableNumber: number;
      customerName?: string;
      paymentMethod: PaymentMethod;
      items: CartItem[];
    }) => {
      const totalKobo = items.reduce(
        (sum, item) => sum + item.menuItem.price_kobo * item.quantity,
        0
      );

      // Create the order with venue/table info
      const { data: order, error: orderError } = await supabase
        .from('orders')
        .insert({
          venue_id: venueId || null,
          table_id: tableId || null,
          table_number: tableNumber,
          customer_name: customerName || null,
          payment_method: paymentMethod,
          total_kobo: totalKobo,
          order_reference: '', // Will be generated by trigger
        })
        .select()
        .single();

      if (orderError) throw orderError;

      // Create order items with snapshots
      const orderItems = items.map((item) => ({
        order_id: order.id,
        menu_item_id: item.menuItem.id,
        quantity: item.quantity,
        unit_price_kobo: item.menuItem.price_kobo,
        item_snapshot: {
          name: item.menuItem.name,
          description: item.menuItem.description,
          price_kobo: item.menuItem.price_kobo,
        },
      }));

      const { error: itemsError } = await supabase
        .from('order_items')
        .insert(orderItems);

      if (itemsError) throw itemsError;

      return order as Order;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['orders'] });
    },
  });
}

export function useUpdateOrderStatus() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({
      orderId,
      status,
    }: {
      orderId: string;
      status: OrderStatus;
    }) => {
      const { data, error } = await supabase
        .from('orders')
        .update({ status })
        .eq('id', orderId)
        .select()
        .single();

      if (error) throw error;
      return data as Order;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['orders'] });
    },
  });
}

export function useConfirmPayment() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (orderId: string) => {
      const { data, error } = await supabase
        .from('orders')
        .update({ payment_confirmed: true, status: 'confirmed' })
        .eq('id', orderId)
        .select()
        .single();

      if (error) throw error;
      return data as Order;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['orders'] });
    },
  });
}

export function useUploadPaymentProof() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({
      orderId,
      file,
    }: {
      orderId: string;
      file: File;
    }) => {
      const fileExt = file.name.split('.').pop();
      const fileName = `${orderId}-${Date.now()}.${fileExt}`;

      const { error: uploadError } = await supabase.storage
        .from('payment-proofs')
        .upload(fileName, file);

      if (uploadError) throw uploadError;

      const { data: { publicUrl } } = supabase.storage
        .from('payment-proofs')
        .getPublicUrl(fileName);

      const { error: insertError } = await supabase
        .from('payment_proofs')
        .insert({
          order_id: orderId,
          image_url: publicUrl,
        });

      if (insertError) throw insertError;

      return publicUrl;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['orders'] });
    },
  });
}
